in-toto-keygen: a command line utility for generating keys
in-toto/in-toto pull request #102
Opened 2017-06-29 14:59 UTC by isachit

A CLI tool for creating key files, and dumping them with filename , filename.pub for private and public keys respectively.
General Usage:
`python in_toto_keygen.py [-p] <filename>`

**Issue Referenced** - #96 

Please note the progress:
- [x] Write the script
- [x] Add Exceptions
- [x] Add Documentation
- [x] Write the unit tests and run them
- [ ] Fix any other issues, and add other functionalities.

@lukpueh and @SantiagoTorres.

UPDATE 1: Added @lukpueh in the author field since he is the one who actually wrote the two functions I have used.
UPDATE 2: It's pretty much in place. Just removing the unnecessary history remains.

2017-06-29 15:04 UTC, isachit commented
I wonder, why aren't @SantiagoTorres  and @lukpueh  in the participants section. :| :/ And also, The travis CI build, along with coveralls. Hm.. Fishy.

2017-06-29 15:05 UTC, isachit commented
Oh yeeesss!!!! Finally!! :D

2017-06-29 16:14 UTC, SantiagoTorres reviewed
Looking good! 👍

2017-06-29 16:14 UTC, SantiagoTorres commented on test/test_in_toto_keygen.py
> +  unittest.main(buffer=True)
Can you end this line with a newline? This usually confuses linecount algorithms and causes off-by-ones on diffing

2017-06-29 16:14 UTC, SantiagoTorres commented on test/test_in_toto_keygen.py
> +"""
In addition to the existing tests, I'm wondering if it'd be nice to have:

1. Create a keypair, and load the public and private keys
2. Create a keypair with different length parameters and load it

2017-06-29 16:25 UTC, isachit commented on test/test_in_toto_keygen.py
> +"""
Alright. On it. :)

2017-06-29 16:26 UTC, isachit commented on test/test_in_toto_keygen.py
> +  unittest.main(buffer=True)
Okay!

2017-06-29 17:31 UTC, isachit commented
@SantiagoTorres  I guess, this is what you suggested right? or?

2017-06-29 17:36 UTC, SantiagoTorres reviewed
Looks good to me. @lukpueh what do you think?

2017-06-29 17:36 UTC, SantiagoTorres commented on in_toto/in_toto_keygen.py
> +  generated. By default it is set as 3072.
Yeah this is good.

2017-06-29 21:14 UTC, lukpueh requested changes
Great work!

 I wonder though why you copied over the code from `in_toto.util`. I thought we had agreed that you will try to use `securesystemslib.keys` directly, or if that's not possible, just use `in_toto.util`.

I'd rather not have the same code twice, especially since I'd like to move that particular code to `securesystemslib.keys` altogether. 

👍  for adding the key length parameter. 
I'd welcome if you changed `in_toto.util. generate_and_write_rsa_keypair` to accept an optional bits parameter and then use that function here.

2017-06-29 21:14 UTC, lukpueh commented on in_toto/in_toto_keygen.py
> +    print('The following error occurred', e)
Please use `log.error` instead of print.

2017-06-29 21:14 UTC, lukpueh commented on in_toto/in_toto_keygen.py
> +                            "multiple of 256.", metavar="<bits>")
Latter is only [partially true](https://github.com/secure-systems-lab/securesystemslib/blob/master/securesystemslib/keys.py#L211-L214) also see the [default crypto library](https://github.com/secure-systems-lab/securesystemslib/blob/master/securesystemslib/settings.py#L49).
I think you can just drop the info here.

2017-07-05 20:16 UTC, merged

2017-07-05 20:16 UTC, lukpueh commented
Great work! Thanks for the PR, @isachit. Out of curiosity, why did you call the branch *nonuke*?

2017-07-05 20:55 UTC, isachit commented
@SantiagoTorres I see what you did there! :D :P Haha. There were some issues with rebasing and removing the commit history not relevant to this PR. So @SantiagoTorres  helped me with that, and while doing it, he made the branch nonuke.

2017-07-06 03:32 UTC, SantiagoTorres commented
[¯\\_(ツ)_/¯](http://i.imgur.com/7A2QTxW.gif)