FIX: gpg/rsa: fix #170 signature length bug
in-toto/in-toto pull request #244
Opened 2018-11-19 21:35 UTC by SantiagoTorres

It appears the specification for PKCSv1.5 doesn't say how long should a
signature should be (i.e., should we zero-pad the signature or should we
use the minimum number of bits required). In this case, signatures
generated using gnupg would sometimes be 8*n bits shorter than the
public key length, which would result in signatures that fail to verify
due to missing leading zeroes (the leading zeroes existed at the bit
level however).

Zero-left-pad signature objects that do not match the length of the exponent
`n` on a gpg rsa public key object before verification.

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #**:

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature:
   I don't want to add a test for this on the interest of runtime of the test-suite, but I'm open to ideas on how to test this..
- [x] Docs have been added for the bug fix or new feature:
   I left a big comment warning future in-toto developers in their pilgrimage through the innards of RFC3447 and RFC4880...

2018-11-19 21:36 UTC, SantiagoTorres commented
I swear to god if tests fail due to some cryptic gpg verification bug **I'll kill and eat a turkey by the end of this week**.

2018-11-19 21:36 UTC, SantiagoTorres commented
related to #171

2018-11-20 03:12 UTC, alyptik approved these changes
Fix looks fine to me, ACK.

2018-11-20 03:16 UTC, alyptik commented
So I think I am starting to kind of see what's going on here. The signatures you are trying to verify with `gpg` actually aren't gpg-generated, just regular PKCS#15 ones from `openssl`? The PGP RFC does require those leading zeros, but I'm guessing PKCS#15 standard doesn't?

Or am I misunderstanding something (originally I had thought these were only gpg-generated keys) here still?

2018-11-20 09:01 UTC, lukpueh requested changes
@SantiagoTorres, you're a hero! I am still not sure how you figured this out, but I'm impressed. :)

Should we remove the `log.debug` statements in `develop` now that we have debugged this? 
https://github.com/in-toto/in-toto/blob/22ebbef7a5b92c5ec527a1c693240c402d8441fe/in_toto/gpg/constants.py#L39-L41
https://github.com/in-toto/in-toto/blob/22ebbef7a5b92c5ec527a1c693240c402d8441fe/in_toto/gpg/functions.py#L94-L96
https://github.com/in-toto/in-toto/blob/22ebbef7a5b92c5ec527a1c693240c402d8441fe/in_toto/gpg/functions.py#L237-L239
https://github.com/in-toto/in-toto/blob/22ebbef7a5b92c5ec527a1c693240c402d8441fe/in_toto/gpg/util.py#L224-L226

2018-11-20 09:01 UTC, lukpueh commented on in_toto/gpg/rsa.py
> +  # deterministically.
Can you fix spelling errors in the comment.
And would you mind describing how you figured out the padding discrepancy? PGP RFC? cryptography code base?

2018-11-20 09:01 UTC, lukpueh commented on in_toto/gpg/rsa.py
> +  if pubkey_length != signature_length: # pragma: no-cover
/no-cover/no cover/

2018-11-20 09:19 UTC, alyptik commented
@lukpueh said:
> @SantiagoTorres, you're a hero! I am still not sure how you figured this out, but I'm impressed. :)
Seconded, never would have thought to check this, ha. The whole subpacket 33 thing seems so silly now.

2018-11-20 09:52 UTC, lukpueh commented
@alyptik, for clarification: The keys and the signatures we are discussing here are indeed generated using gpg. We call the gpg2 command line tool for signing, using a key in the keychain, identified via keyid (or the default key, if no keyid is specified). And we also use the gpg2 command line tool to export public keys so that they can be e.g. added to an in-toto layout.

However, signature verification is performed without gpg. For that we use `pyca/cryptography`.

2018-11-20 10:27 UTC, alyptik commented
@lukpueh Aha, I see. Thanks for the clarification.

2018-11-20 17:33 UTC, SantiagoTorres commented
@lukpueh Let me know if this is what you had in mind. Cheers!

2018-11-20 19:11 UTC, lukpueh approved these changes

2018-11-20 19:11 UTC, merged