Fix summary link naming
in-toto/in-toto pull request #256
Opened 2019-02-25 20:51 UTC by adityasaky

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #**: #254 

**Description of the changes being introduced by the pull request**:

I've implemented the same fix used in the golang repository - see in-toto/in-toto-golang#19.

2019-02-25 21:39 UTC, trishankatdatadog commented
What is a "summary link?" First time I ever heard about it.

2019-02-25 21:56 UTC, adityasaky commented
Summary links are used during sublayout verification  - a link summarizes the steps in the sublayout and takes its place. Right now, the name of a summary link is set as the name of the first link of the sublayout. When I was working on in-toto/in-toto-golang, @lukpueh and I realized this could be a potential problem, and this is a simple fix to use the corresponding step name instead. See: #254

2019-03-01 14:05 UTC, lukpueh requested changes
Thanks for the PR, @adityasaky! Please consider addressing my inline suggestions. Also, would you mind adding a test, where a MATCH rule of a super layout refers to the step, represented by the (now correctly named) summary link of a sublayout? (see #254)

2019-03-01 14:05 UTC, lukpueh commented on in_toto/verifylib.py
> +            verification.
Minor suggestions: I think the description and the name give more context about the *usual* way of calling `get_summary_link` than necessary. I'd just call the parameter `name` or `link_name` and  say that it is the name assigned to the link.

2019-03-01 14:05 UTC, lukpueh commented on in_toto/verifylib.py
> +            verification to generate summary links.
Maybe it is worth pointing out that the parameter is used in recursive calls of `in_toto_verify` and to refer the reader to `verify_sublayouts` to see how it is used?

2019-03-04 18:48 UTC, SantiagoTorres approved these changes
LGTM

2019-03-05 09:57 UTC, lukpueh commented
Thanks for addressing my concerns, @adityasaky. Can you please add the requested test?

2019-03-05 14:48 UTC, adityasaky commented
Yep, I'm working on that @lukpueh.

2019-03-05 19:58 UTC, adityasaky commented
I think this suffices, @lukpueh.

2019-03-06 08:36 UTC, lukpueh approved these changes

2019-03-06 08:37 UTC, merged

2019-03-06 08:38 UTC, lukpueh commented
Thanks for the awesome work, @adityasaky! In addition to reviewing your code I ran the test in debug mode and all looks good to me.