Removes OO form matchrules, updates AS PATH
in-toto/in-toto pull request #31
Opened 2016-11-02 19:58 UTC by lukpueh

- Matchrules are no longer OO
  they are simply stored as list and all the verification happens
  in verifylib
- This also fixes #14, an ugly workaround to use attr's asdict
- The commit also updates the MATCH matchrules to take an
  optional target path which allows for matching artifacts that
  have different paths

2016-11-02 21:13 UTC, SantiagoTorres requested changes
Some minor nits only. Thanks!

2016-11-02 21:13 UTC, SantiagoTorres commented on toto/verifylib.py
> +    That the target_link as idetfied by ("FROM" <step>) exists in
identified*

2016-11-02 21:13 UTC, SantiagoTorres commented on toto/verifylib.py
> +    RuleVerficationFailed
When this is raised would be good saying here.

2016-11-02 21:13 UTC, SantiagoTorres commented on toto/verifylib.py
> +      ComparableHashDict(target_artifacts[target_path])):
Using these `ComparableHashDicts` is the way to go? couldn't we just compare fields within the source/target paths?

I wonder if this is an issue if, for example, one link provides two hashes and the other one provides only one.

This is a minor nit though.

2016-11-02 21:13 UTC, SantiagoTorres commented on toto/verifylib.py
> +    RuleVerficationFailed
same here

2016-11-02 21:13 UTC, SantiagoTorres commented on toto/verifylib.py
> +    raise RuleVerficationFailed("'%s' " \
I don't think you need the `\` here

2016-11-02 21:13 UTC, SantiagoTorres commented on toto/verifylib.py
> +    Calls the respective verify_<rule-type>_rule function.
Is this really a side-effect?

2016-11-02 21:13 UTC, SantiagoTorres commented on toto/verifylib.py
> +    Calls helper functions to verify all matchrules of an item.
Is this a side-effect?

2016-11-02 21:23 UTC, lukpueh commented on toto/verifylib.py
> +    RuleVerficationFailed
Okay, will give more info.

2016-11-02 21:27 UTC, lukpueh commented on toto/verifylib.py
> +      ComparableHashDict(target_artifacts[target_path])):
`ComparableHashDicts` is just a helper I wrote to compare two hash dicts of format `ssl_crypto.formats.HASHDICT_SCHEMA`, e.g.

``` python
{'sha256': '23432df87ab..',
'sha512': '34324abc34df..', ...}
```

The behavior is documented in its docstring:

``` python
    """Equal if the dicts have the same keys and the according values
    (strings) are equal"""
```

But we can talk about changing the behavior. Using it seems handy though.

2016-11-02 21:27 UTC, lukpueh commented on toto/verifylib.py
> +    RuleVerficationFailed
Will change.

2016-11-02 21:27 UTC, lukpueh commented on toto/verifylib.py
> +    raise RuleVerficationFailed("'%s' " \
Will change.

2016-11-02 21:33 UTC, lukpueh commented on toto/verifylib.py
> +    Calls the respective verify_<rule-type>_rule function.
You are right. I don't think it is a side-effect either. I guess I saw some similar "side effects" in the tuf projects and adapted the broad understanding. I'll take this out here.

2016-11-02 21:33 UTC, lukpueh commented on toto/verifylib.py
> +    Calls helper functions to verify all matchrules of an item.
See https://github.com/in-toto/in-toto/pull/31#discussion_r86243521

2016-11-03 15:29 UTC, SantiagoTorres commented on toto/verifylib.py
> +      ComparableHashDict(target_artifacts[target_path])):
Yeah, this was my bad. I think the current behavior is ok for the time being.

2016-11-03 15:30 UTC, SantiagoTorres approved these changes

2016-11-03 15:30 UTC, SantiagoTorres commented
👍 Thanks!

2016-11-03 15:30 UTC, merged