doc: add command line tools
in-toto/in-toto pull request #332
Opened 2019-11-26 23:52 UTC by SantiagoTorres

**Fixes issue #**:
None

**Description of the changes being introduced by the pull request**:

This PR adds a small series of documents to describe the current CLI tools. These are not meant to be exhaustive (i.e., to include every single command line argument), but rather to provide a little insight on how these tools can be used.

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [N/A] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

2019-11-27 13:10 UTC, lukpueh reviewed
Thanks a lot for taking a stab at this, @SantiagoTorres! This is really awesome. I left a couple of comments. Mostly minor typo fixes. 

Btw. did you take a look at the output of `in-toto-{run, record, verify, sign} --help`? There should be more usage examples that might be useful here.

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-mock.rst
> +metadata, inspect it and sign if afterwards.
```suggestion
metadata, inspect it and sign it afterwards, e.g. using :doc:`in-toto-sign`.
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-mock.rst
> +    # use in-toto sign to sign
```suggestion
    # use in-toto-sign to sign
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-mock.rst
> +    # link touch.xxxxxx.link is created hedre
```suggestion
    # link touch.xxxxxx.link is created here
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-record.rst
> +
Should this also be a "Usage Example" section?

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-run.rst
> +carrying out a step. To do this, ir wraps any command passes and attempts to
```suggestion
carrying out a step. To do this, it wraps any command passed, and attempts to
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-run.rst
> +in-toto run is the main wrapper for in-toto to generate link metadata whlie
```suggestion
in-toto run is the main wrapper for in-toto to generate link metadata while
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-mock.rst
> +to pass a name paramter using ``--name`` or ``-n`` parameter. Other parameters
```suggestion
to pass a name parameter using ``--name`` or ``-n`` parameter. Other parameters
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-run.rst
> +  rsa or ed25519 keys, created with :doc:`in-toto-keygen` or a PKCSv7/11 PEM
Are you sure that this is PKCSv7/11?

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-verify.rst
> +in-toto-verify only accepts to paramters: the location of the layout file and
```suggestion
in-toto-verify only accepts two parameters: the location of the layout file and
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-run.rst
> +Generating a pice of link metadata with no materials, but products (e.g., when
```suggestion
Generating a piece of link metadata with no materials, but products (e.g., when
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-run.rst
> +--------
Should the materials and products "example" be in the Examples section? Also, the other documents call the section "Usage Examples". Is it worth making this consistent?

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-run.rst
> +    in-toto-run -k mykey -n myname -m . -p build
The example should probably have a `-- <cmd>` argument.

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-run.rst
> +    in-toto-run -k mykey -n myname -p foo.c
The example should probably have a `-- <cmd>` argument.

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-sign.rst
> +    # a signed root.layout is created
This is not accurate. The signature is actually written to mylayout.layout

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-keygen.rst
> +Basic usage
Similar section heads are title case. I suggest choosing a consistent case:
```suggestion
Basic Usage
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-verify.rst
> +Link file location
Most of the section heads use title case. I think this should be consistent. I.e.:

```suggestion
Link File Location
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/index.rst
> +Command line tools
See other comments about consistent section header case. I suggest.:

```suggestion
Command Line Tools
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-verify.rst
> +then continue veriication following the policy specified in the layout itself.
```suggestion
then continue verification following the policy specified in the layout itself.
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-verify.rst
> +Links need be in the current directory, and they must be named
```suggestion
Links need to be in the current directory, and they must be named
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-verify.rst
> +named `stepname.keyidprefix`, where all the links relevants to that sublayout
```suggestion
named `stepname.keyidprefix`, where all the links relevant to that sublayout
```

2019-11-27 13:10 UTC, lukpueh commented on doc/source/command-line-tools/in-toto-verify.rst
> +must exist. The sublayout itself will be contaiend where the link file usually
```suggestion
must exist. The sublayout itself will be contained where the link file usually
```

2019-12-09 20:56 UTC, SantiagoTorres commented
@lukpueh I think this is ready for another go. Thanks for the review!

One note is that I didn't know (or could think of) other usage examples for in-toto-record, so I wonder if we'd like to leave it  as-is and then add whenever inspiration hits us

2019-12-11 10:45 UTC, lukpueh requested changes
Thanks for the changes, @SantiagoTorres! Are you sure you pushed everything? There are still many (11) unaddressed comments from my last review, including typo fix suggestions.

2019-12-23 17:15 UTC, SantiagoTorres commented on doc/source/command-line-tools/in-toto-sign.rst
> +    # a signed root.layout is created
hmm, after re-reading the help I just noticed this. I should've cleaned my testing dir better. 

I'm starting to think this is not the most obvious behavior though. What do you think?

2020-02-26 14:15 UTC, lukpueh commented
@SantiagoTorres, should we close here and merge in #341?

2020-02-26 15:40 UTC, SantiagoTorres commented
we're opting for #341

2020-02-26 15:40 UTC, closed without merging