Update for python 3.10 compatibility
in-toto/in-toto pull request #480
Opened 2021-12-05 13:41 UTC by inglor

Signed-off-by: Leonidas Spyropoulos <artafinde@gmail.com>

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #00:
N/A

**Description of the changes being introduced by the pull request**:
Fix compatibility with Python 3.10

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [x] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

2021-12-06 08:38 UTC, lukpueh requested changes
Thanks for the contribution, @inglor! Would you mind adding 3.10 to CI/CD? IIRC, this should be a matter of patching...
https://github.com/in-toto/in-toto/blob/fa124f2aefb40e2b36fff4fef1dda36d14b65945/.github/workflows/ci.yml#L12
and
https://github.com/in-toto/in-toto/blob/fa124f2aefb40e2b36fff4fef1dda36d14b65945/tox.ini#L8

Also, it would be nice if we performed the version case handling only once, e.g. define a global in `common_args.py` along the lines of:
```python
 OPTS_TITLE = "Optional Arguments" if sys.version_info < (3, 10) else "Options"
```
which could be used in all other files (and maybe `lower()`ed in the usage texts)

2021-12-06 09:18 UTC, inglor commented
Hi @lukpueh thanks for the review! Changes applied. I've modified the CI/CD to include 3.10 now - hope checks pass again :)

2021-12-07 09:13 UTC, lukpueh approved these changes

2021-12-07 09:13 UTC, lukpueh commented
Many thanks, @inglor!

2021-12-07 09:13 UTC, merged