Totosprint add submodules
in-toto/in-toto pull request #49
Opened 2016-11-21 20:03 UTC by baloyan

Removed ssl_commons directory and created ssl_commons submodule.

Changed In-Toto old ssl_crypto submodule into the new ssl_crypto submodule, which is commons for
In-Toto and TuF.

Fixed unittest bugs

2016-11-22 21:38 UTC, lukpueh requested changes
Thanks for the additions
- Please fix conflict in .gitmodules
- Please fix typos in commit message (2e7499)
- This PR moves the ssl_crypto submodule pointer from [542caed](https://github.com/secure-systems-lab/ssl_crypto/commit/542caedfc2c1d60f6d30ae1188aa68ad7cb7a389) to [ff19a50](https://github.com/secure-systems-lab/ssl_crypto/commit/ff19a508023cec859a3e2bc3a897030075743792) (9 commits). It would be nice to summarize those changes in this PR's description
- ssl_crypto@ff19a50 has failing unittests:
```
======================================================================
ERROR: test_create_signature (toto.ssl_crypto.tests.test_keys.TestKeys)
----------------------------------------------------------------------
ValueError: The required private key is unset.

======================================================================
ERROR: test_decrypt_key (toto.ssl_crypto.tests.test_keys.TestKeys)
----------------------------------------------------------------------
FormatError: Key object does not contain a private part.

======================================================================
ERROR: test_format_metadata_to_key (toto.ssl_crypto.tests.test_keys.TestKeys)
----------------------------------------------------------------------
FormatError: Wanted a u'RSAKEY_SCHEMA'.

======================================================================
ERROR: test_verify_signature (toto.ssl_crypto.tests.test_keys.TestKeys)
----------------------------------------------------------------------
FormatError: Missing key 'keyid' in u'ANYKEY_SCHEMA'
```

2016-11-22 22:05 UTC, lukpueh commented on .gitmodules
> +	url = https://github.com/secure-systems-lab/ssl_crypto.git
Please use [spaces instead of tabs](https://github.com/secure-systems-lab/code-style-guidelines#tabs).

2016-12-01 18:24 UTC, SantiagoTorres requested changes

2016-12-01 18:24 UTC, SantiagoTorres commented on toto/settings.py
> +REPOSITORY_HASH_ALGORITHMS = ['sha256', 'sha512']
Are these relevant to Toto?

2017-01-05 19:25 UTC, lukpueh commented
The architecture has changed https://github.com/in-toto/in-toto/issues/45#issuecomment-270733005, which makes above changes obsolete. Thanks for the work. I'll herby close this PR as "won't merge".

2017-01-05 19:25 UTC, closed without merging