Adds continuous integration setup with tox and coverage
in-toto/in-toto pull request #50
Opened 2016-11-21 20:58 UTC by lukpueh

- Decorates not implemented unittests to be skipped
- Updates tox.ini to install requirements, run coverage and call `runtests.py` instead of `setup.py test`.
- Updates .travis.yml to use tox and coveralls

2016-11-21 21:39 UTC, lukpueh commented
Let's make this a 100%!

2016-11-21 23:34 UTC, SantiagoTorres requested changes

2016-11-21 23:34 UTC, SantiagoTorres commented on .travis.yml
> +    coveralls
it'd be nice if we had a newline here

2016-11-21 23:34 UTC, SantiagoTorres commented on test/test_toto_verify.py
> +
can we remove this whitespace?

2016-11-21 23:34 UTC, SantiagoTorres commented on tox.ini
> +    coverage
maybe we could create a file called requirements-ci.txt and add these there. Just keep -rrequirements-ci.txt...

2016-11-21 23:34 UTC, SantiagoTorres commented on tox.ini
> +    # PYTHONPATH = {toxinidir}
Do we need this commented out?

2016-11-23 00:23 UTC, SantiagoTorres approved these changes

2016-11-23 00:23 UTC, SantiagoTorres commented
@lukpueh I think this is ready to merge? 👍

2016-11-23 00:24 UTC, lukpueh commented
Thanks for the review, @SantiagoTorres!

2016-11-23 00:24 UTC, merged