Add dirHash resolver
in-toto/in-toto pull request #590
Opened 2023-05-05 17:38 UTC by adityasaky

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #**: N/A

**Description of the changes being introduced by the pull request**:

Adds implementation of a dirHash resolver as described in https://github.com/in-toto/attestation/blob/main/spec/v1.0/digest_set.md#dirhash.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

2023-05-05 17:51 UTC, adityasaky commented
Some interesting results here, I suspect it's because of the `locale.setlocale` not matching up. :thinking:

2023-05-05 18:01 UTC, adityasaky commented
`locale.setlocale` wasn't sufficient for both `LC_ALL` and `LC_COLLATE` on MacOS and Windows. I need to read the docs to identify how to differentiate by platform here (I'm mostly surprised MacOS isn't working) but it'll have to be later. In the meantime, @lukpueh if you have any tips, lmk!

2023-05-05 18:01 UTC, adityasaky commented
Perhaps running https://github.com/in-toto/attestation/blob/main/spec/v1.0/digest_set.md#dirhash locally on MacOS would shed some light as well.

2023-05-08 14:33 UTC, lukpueh commented
> In the meantime, @lukpueh if you have any tips, lmk!

Unfortunately, I don't.

> Perhaps running https://github.com/in-toto/attestation/blob/main/spec/v1.0/digest_set.md#dirhash locally on MacOS would shed some light as well.

The link 404s

2023-05-08 14:34 UTC, adityasaky commented
> https://github.com/in-toto/attestation/blob/main/spec/v1/digest_set.md#dirhash

The link changed to drop the `.0` from the spec version. Here's the new one!

2023-05-08 14:35 UTC, adityasaky commented
This is the command:

`find . -type f | cut -c3- | LC_ALL=C sort | xargs -r sha256sum | sha256sum | cut -f1 -d' '`

2023-05-08 15:01 UTC, lukpueh commented
Here's what I get from within `/tests/resolver/dir_resolver`:

```bash
find . -type f | cut -c3- | LC_ALL=C sort | xargs -r sha256sum | sha256sum | cut -f1 -d' '
065702044fb68ae689c8cf9ae62d33ea974bc7107dc6c1fff73028f2e7411431
```

But the more interesting bit wrt your failing tests on macOS and Windows  is probably the git clone warning about case-sensitive paths n a case-insensitive fs:

```bash
git clone -b add-dirhash-resolver git@github.com:adityasaky/in-toto.git in-toto-aditya
Cloning into 'in-toto-aditya'...
remote: Enumerating objects: 9504, done.
remote: Counting objects: 100% (730/730), done.
remote: Compressing objects: 100% (286/286), done.
remote: Total 9504 (delta 466), reused 637 (delta 424), pack-reused 8774
Receiving objects: 100% (9504/9504), 2.67 MiB | 3.60 MiB/s, done.
Resolving deltas: 100% (6595/6595), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'tests/resolver/dir_resolver/subdir/A.txt'
  'tests/resolver/dir_resolver/subdir/a.txt'
  'tests/resolver/dir_resolver/subdir/B.txt'
  'tests/resolver/dir_resolver/subdir/b.txt'
```

2023-05-08 16:06 UTC, adityasaky commented
Thanks @lukpueh, that was helpful. The macOS failure was indeed because of the case insensitive collision. That leaves Windows to work out.

2023-05-09 07:39 UTC, lukpueh commented
> That leaves Windows to work out.

I've often used https://github.com/mxschmitt/action-tmate lately to figure out breaking CI on Windows runners

2023-05-12 18:28 UTC, adityasaky commented
Thanks, that was helpful! I've taken the liberty of not allowing users to pass in `normalize_line_endings`, instead setting it to true always. That turned out to be the mismatch.

2023-05-16 09:29 UTC, lukpueh requested changes
Cool stuff, @adityasaky! This should work, but I'm a little worried about surprising behaviour, especially since your config parameters may be relevant for DirectoryResolver itself, but also for the FileResolver used under the hood. How this currently works is not obvious, at least to me. More specifically, why are all but one parameters passed on to FileResolver? 

I can see good reasons to do it the way you do it, but also good reasons to do it differently. Here are some thoughts.

- The original purpose of `lstrip_path`s and `base_path` was to not have absolute paths in materials/products dicts. I think they should stay in DirectoryResolver, to affect the returned URIs and not be passed on to FileResolver, where they affect the hash. Also, you may consider supporting only one of them.
- Instead of passing `base_path` to FileResolver, I suggest to create a new FileResolver for each path in the passed URIs, and pass that path as `base_path` for FileResolver. This maps well to the `find <path> ...` command, which prints file names, relative to <path>. This should also make the hash of a directory reproducible, regardless of these arguments.
- Applying `exclude_patterns` on the URIs explicitly passed to `DirectoryResolver` probably does not make sense. Still, if they are only used inside `FileResolver` this should be documented.
- The `follow_symlink_dirs` and `normalize_line_endings` obviously belong to FileResolver. Should both be configurable via DirectoryResolver? Currently, only `follow_symlink_dirs` is.

2023-05-16 09:29 UTC, lukpueh commented on tests/test_directory_resolver.py
> +"""
nit: I suggest we drop the doc header boilerplate in new modules.

2023-05-16 09:29 UTC, lukpueh commented on tests/test_directory_resolver.py
> +        resolver = DirectoryResolver(base_path="tests/resolver")
https://github.com/in-toto/in-toto/pull/585#discussion_r1188664663

2023-05-16 09:29 UTC, lukpueh commented on tests/test_directory_resolver.py
> +        resolver = DirectoryResolver(base_path="tests/resolver")
same applies below

2023-05-16 09:29 UTC, lukpueh commented on tests/test_directory_resolver.py
> +        resolver = DirectoryResolver(base_path="tests/resolver")
`Path(__file__).parent / "tests" / "resolver"` could be a module global.

2023-05-16 09:29 UTC, lukpueh commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
Oh interesting. Just realized that the paths are included when calculating the hash. That is why the hash is different  for different combinations of base_path, lstrip_paths and uri arguments, even if they record the same files.

Is this obvious to the typical `DirectoryResolver` user? I think it should be documented somewhere.

2023-05-16 09:29 UTC, lukpueh commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
Also, is this expected to be cross-platform compatible? Or what's the output of `find` on Windows? What path separators does it use?

2023-05-16 09:29 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +            if len(exhaustive_hashes) == 0:
Thy pythonic way would be...
```suggestion
            if not exhaustive_hashes:
```

2023-05-16 09:29 UTC, lukpueh commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
I see you use file resolver to replicate `find . -type f | cut -c3- | LC_ALL=C sort | xargs -r sha256sum`. I think this should be briefly mentioned, especially since FileResolver does some very opinionated file name mangling, which very likely differs form above command.

2023-05-16 09:29 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +    def _hash(self, exhaustive_hashes):
nit: `exhaustive_hashes` is a long and not very descriptive name. Would `file_hashes` also make sense?

2023-05-16 09:29 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +        for path in uris:
What's the expected behaviour if `path` is not a directory?

2023-05-16 09:29 UTC, lukpueh commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
Oh, _lstrip_paths isn't passed on to FileResolver, so this is not considered when calculating the hash. This means base_path is responsible for the different hashes?

2023-05-16 09:29 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +        path = path.replace("\\", "/")
See https://github.com/in-toto/in-toto/issues/565.

2023-05-16 09:29 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +        if self._lstrip_paths and path in existing_paths:
See https://github.com/in-toto/in-toto/issues/601.

2023-05-16 12:36 UTC, adityasaky commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
No, normalize_file_endings was responsible for the differences. I've set that to True always now.

2023-05-16 12:43 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +        for path in uris:
Good call. I think if it's a file it just hashes that one file and moves on. Should we check at this point and `continue` or error out?

2023-05-16 12:48 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +        for path in uris:
I've added a check to `continue` and a test, lmk what you think.

2023-05-17 08:37 UTC, lukpueh commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
I meant different hashes in `test_regular_directory` and `test_regular_directory_with_lstrip`

2023-05-22 14:49 UTC, adityasaky commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
Correct, in the second example, the hash is recorded from a different directory so the path per file is different.

I can see that being confusing though. Should we drop one of lstrip / base_path? Alternatively, we can pass lstrip to the file resolver too and make it fully consistent.

2023-05-22 14:56 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +        if self._lstrip_paths and path in existing_paths:
My suggestion is the check happens here: https://github.com/in-toto/in-toto/blob/develop/in_toto/runlib.py#L187, the snippet in the issue as well.

That way a resolver instance is only responsible for its own internal collisions.

2023-05-22 14:56 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +        path = path.replace("\\", "/")
Do you suggest removing this altogether?

2023-05-23 07:30 UTC, lukpueh commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
> Should we drop one of lstrip / base_path? Alternatively, we can pass lstrip to the file resolver too and make it fully consistent.

Did you see my review summary comment above? https://github.com/in-toto/in-toto/pull/590#pullrequestreview-1427805634

2023-05-23 07:43 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +        path = path.replace("\\", "/")
I think cross-platform metadata consistency is still the goal, right? Why not use a standard file/directory path representation as #565 suggests?

If you want something quick, I suggest to leave it as is. But at some point we should address the issue, and we should probably do this in `FileResolver`, which also still uses this hack.

2023-05-23 07:47 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +        if self._lstrip_paths and path in existing_paths:
Agreed! If we check, we should check in both places. #601 also suggests to just warn instead of raising an error. What do you think?

2023-05-23 08:09 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +        for path in uris:
I think either way is fine. Maybe add a log statement?  Regardless, the base path join you do here seems overly complicated. Did you read my comment about base_path in the review summary https://github.com/in-toto/in-toto/pull/590#pullrequestreview-1427805634?

2023-05-24 20:35 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +        if self._lstrip_paths and path in existing_paths:
I responded there. I don't know that this is in scope of this PR, resolving this thread for now.

2023-05-24 20:35 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +        path = path.replace("\\", "/")
I've removed this entirely. The tests now don't use hard coded paths any more so there aren't any errors either.

2023-05-24 20:40 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +        for path in uris:
Added a log statement.

2023-05-24 20:41 UTC, adityasaky commented on tests/test_directory_resolver.py
> +                "sha256": "87454edb176e16e396856e5be6c73ae51659785aa65999f3b51ff06d8fc59b8e"
I've dropped base path altogether, I pass on the dir path in each instance as base path to the file resolver, then hashing `["."]` to directly mimic the CLI commands.

2023-06-06 11:25 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +            if not file_hashes:  # pragma: no cover
Why `# pragma: no cover`? Can this not be tested? If you just don't have a test yet, I think it's more transparent to let coveralls flag it.

2023-06-06 11:25 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +    `normalize_line_endings` are passed on to the `FileResolver` instance.
nit: I think this could be more user friendly. The caller does not really need to know about `FileResolver`. Maybe something along the lines *... `exclude_patterns` are not applied on the directory paths passed to hash_artifacts, but only on the files inside the directory. Similarly, `follow_symlink_dirs` and `normalize_line_endings` are used on subdirectories and files inside ...*

2023-06-06 11:25 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +                continue
I know I said that a warning seems fine. But maybe your [argument](https://github.com/in-toto/in-toto/issues/601#issuecomment-1561890703) about unexpected metadata results being a good reason for erroring out also applies here? It seem like a usage error if you pass a file path to a directory hasher.

2023-06-06 11:25 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +            if not file_hashes:  # pragma: no cover
Regardless, is skipping empty directory correct? The `find` command you are trying to replicate does return a hash in an empty directory, that of an empty string (w/o newline). Should your _hash function support that?

2023-06-06 11:25 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +        path = path.replace("\\", "/")
But this means, that artifact paths in link metadata will be different on different platforms.

2023-06-06 11:33 UTC, lukpueh commented on in_toto/resolver/_resolver.py
> +        path = path.replace("\\", "/")
And it makes lstrip paths, as they are implemented now, platform dependent too.

2023-06-06 11:39 UTC, lukpueh requested changes
This looks quite good modulo some minor nits inline. Do you want to move forward without cross-platform consistency? I'm okay with it, but at some point we should figure out what's right here.

2023-06-06 14:13 UTC, lukpueh commented on tests/test_directory_resolver.py
> +        target_path = f"{parent_path}dir_resolver"
This test (and the next one) won't work on a platform that requires backslashes as path separators. I think you should:

```suggestion
        lstrip_path = f"{Path(__file__).parent}/resolver/"
        target_path = str(Path(__file__).parent / "resolver" / "dir_resolver")
```

2023-06-06 14:19 UTC, lukpueh commented on tests/test_directory_resolver.py
> +        target_path = f"{parent_path}dir_resolver"
... of course this requires normalising the path before lstripping.

2023-07-18 14:55 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +            if not file_hashes:  # pragma: no cover
Good point! Updated to support recording empty dir with corresponding change to test.

2023-07-18 15:09 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +                continue
Updated!

2023-07-18 15:22 UTC, adityasaky commented on in_toto/resolver/_resolver.py
> +        path = path.replace("\\", "/")
Good point. I've added them back, shall we pick this up outside the context of this PR across all resolvers?

2023-07-18 16:00 UTC, adityasaky commented
FYI: I'll rebase and squash after this is good to go.

2023-07-19 12:49 UTC, lukpueh approved these changes
Great work, @adityasaky. LGTM!

2023-07-19 13:51 UTC, merged