Enhance separation between in-toto-run cli tool and library
in-toto/in-toto pull request #60
Opened 2017-01-06 16:12 UTC by lukpueh

Moves complete in_toto_run workflow to `runlib.in_toto_run`. 

The user-facing in-toto-run command line tool just takes care of command line argument parsing and calls `runlib.in_toto_run`. In case an exception occurs it is caught in the calling CLI tool, which exits gracefully.

The CLI tool also takes care of loading the key from disk potentially prompting for a password which should not happen in the library.
- Adds an optional `--verbose` flag to `in-toto-run` CLI tool that turns on logging statements in the library.
- Makes `runlib.in_toto_run`'s key argument optional, so that it can also be used when running inspections, which do not need to sign generated link metadata.
- Changes `verifylib` to dump link metadata when running inspections.
- Enhances logging statements in runlib.
- in_toto_run/runlib is now similarly structured as in_toto_record/runlib. See discussion in https://github.com/in-toto/in-toto/issues/6#issuecomment-263988714.

2017-01-09 19:12 UTC, SantiagoTorres requested changes
Minor details/questions on this one. Thanks!

2017-01-09 19:12 UTC, SantiagoTorres commented on in_toto/in_toto_run.py
> +from in_toto import log
👍

2017-01-09 19:12 UTC, SantiagoTorres commented on in_toto/in_toto_run.py
> +if __name__ == "__main__":
This is the CLI tool right? when we log.error, does it pint to the terminal, or is it silently failing right now?

2017-01-09 19:12 UTC, SantiagoTorres commented on in_toto/in_toto_run.py
> +    sys.exit(1)
Funny quirk (I've never stopped to think about this):

```python
santiago at ~ ✔ bpython
bpython version 0.16 on top of Python 3.5.2 /usr/bin/python
>>> import sys
>>> sys.exit(-1)
(-1,)
santiago at ~ ✗ echo $?
1
santiago at ~ ✔ bpython
bpython version 0.16 on top of Python 3.5.2 /usr/bin/python
>>> import sys
>>> sys.exit(1)
(1,)
santiago at ~ ✗ echo $?
1
```

2017-01-09 19:12 UTC, SantiagoTorres commented on in_toto/runlib.py
> +    link.sign(key)
Hmm, I wonder if we want to try to load the key before we actually run anything...

2017-01-09 19:12 UTC, SantiagoTorres commented on test/test_in_toto_run.py
> +
Minor nit: this is too much whitespace isn't it?

2017-01-09 19:12 UTC, SantiagoTorres commented on test/test_in_toto_run.py
> +      in_toto_run_main()
I know that checking that there was a file written or not is better than checking that a link metadata object is not returned, but maybe we could do both?

2017-01-09 19:12 UTC, SantiagoTorres commented on test/test_runlib.py
> +  link_cmd_args, key=False, record_byproducts=False). """
I'm not sure if this type of comment is descriptive enough.

2017-01-09 19:12 UTC, SantiagoTorres commented on test/test_toto_run.py
> -  unittest.main()
👍

2017-01-09 19:17 UTC, lukpueh commented on demo/run_demo.py
> +      "final_product/tar.link",
We didn't dump inspections before, ergo there was no `tar.link`.  `verifylib. run_all_inspections` now calls `runlib.in_toto_run` which also dumps the metadata file, which we wanted to add for inspections (auditing reasons) anyway. Therefor, I also remove this file when clearing the demo final_product.

2017-01-09 19:24 UTC, lukpueh commented on in_toto/in_toto_run.py
> +    sys.exit(1)
Apparently `exit` only uses the least significant 8 bits, i.e. [0-255].

2017-01-09 19:31 UTC, lukpueh commented on in_toto/in_toto_run.py
> +if __name__ == "__main__":
Is this question related to the quotes in L150? 

Whether `log.error` prints or not depends on the logging level specified in `settings.py` and if the `--verbose` cli option is specified, which overrides the level in `settings.py` to print everything greater than `logging.INFO`.

2017-01-09 19:34 UTC, lukpueh commented on in_toto/runlib.py
> +    link.sign(key)
That's what we currently do. The key is loaded in the command line tool and passed to `runlib.in_toto_run`. See https://github.com/in-toto/in-toto/blob/87e3ddee7442fdec058ef44fe523108fdc1a013b/in_toto/in_toto_run.py#L139-L145

2017-01-09 19:34 UTC, lukpueh commented on test/test_in_toto_run.py
> +
Yeah, I guess it is. Will change.

2017-01-09 19:37 UTC, lukpueh commented on test/test_runlib.py
> +  link_cmd_args, key=False, record_byproducts=False). """
Hm. It is the TestCase level description. All test functions of this TestCase test the in_toto_run function. How it is tested is explained in each test function's docstring. But I can elaborate if you want me to.

2017-01-09 19:37 UTC, lukpueh commented on test/test_in_toto_run.py
> +      in_toto_run_main()
Yep. I can change this.

2017-01-09 19:43 UTC, SantiagoTorres commented on in_toto/runlib.py
> +    link.sign(key)
Are you sure? if we pass a path here to a key that does not exist (and maybe is not called using in-toto-run, we will run the command and then fail after we fail to load the key.

2017-01-09 19:44 UTC, SantiagoTorres commented on test/test_runlib.py
> +  link_cmd_args, key=False, record_byproducts=False). """
what it feels like is as if you copied the function's signature for reference or something. Do you think that having the parameters in here helps at all?

2017-01-09 19:45 UTC, lukpueh commented on in_toto/runlib.py
> +    link.sign(key)
Correct. We should check on top of the function that the key is properly formatted.

2017-01-09 19:46 UTC, lukpueh commented on test/test_runlib.py
> +  link_cmd_args, key=False, record_byproducts=False). """
Correct. I copied the signature to know what valid/invalid arguments I should test the function with. :)

2017-01-09 19:48 UTC, SantiagoTorres commented on test/test_runlib.py
> +  link_cmd_args, key=False, record_byproducts=False). """
lol, I do the same thing :P

The way I see it, we could either remove them, or list them and say what a "valid" range of each parameter would look like (I think the former is less of a hassle tho)

2017-01-09 21:01 UTC, lukpueh commented on in_toto/in_toto_run.py
> +if __name__ == "__main__":
Maybe you want to add you thoughts on this to https://github.com/in-toto/in-toto/issues/6?

2017-01-09 21:03 UTC, lukpueh commented on test/test_runlib.py
> +  link_cmd_args, key=False, record_byproducts=False). """
Actually I did this in all my TestCases's class level docstrings so far. Is your concern worth a ticket? :)

2017-01-09 22:02 UTC, SantiagoTorres commented on test/test_runlib.py
> +  link_cmd_args, key=False, record_byproducts=False). """
Nah, it's definitely not a big deal :)

2017-01-12 17:00 UTC, lukpueh commented on test/test_in_toto_run.py
> +      in_toto_run_main()
Just realized that this test actually calls the command `in-toto-run`, which does not return a link metadata object. Only the library function `runlib.in_toto_run` does.

2017-01-13 17:13 UTC, lukpueh commented on demo/run_demo.py
> +      "final_product/tar.link",
No fix needed

2017-01-13 17:13 UTC, lukpueh commented on in_toto/in_toto_run.py
> +    sys.exit(1)
No fix needed

2017-01-13 17:13 UTC, lukpueh commented on in_toto/in_toto_run.py
> +if __name__ == "__main__":
No fix needed

2017-01-13 17:13 UTC, lukpueh commented on in_toto/runlib.py
> +    link.sign(key)
Fixed in https://github.com/in-toto/in-toto/pull/60/commits/f94843c4cf01ac057dec1a5b19a45a2648fb55de

2017-01-13 17:13 UTC, lukpueh commented on test/test_in_toto_run.py
> +      in_toto_run_main()
No fix needed

2017-01-13 17:20 UTC, SantiagoTorres commented on in_toto/in_toto_run.py
> +if __name__ == "__main__":
my question is: what happens if the logger's handler is a file handler?

2017-01-13 17:25 UTC, lukpueh commented on in_toto/in_toto_run.py
> +if __name__ == "__main__":
Well, right now the logger does not have file handler. And it is on us to decide how the logger is used. :)

I'd like to improve logging/user feedback in general (cf. https://github.com/in-toto/in-toto/issues/6). E.g. properly separate logging (which could use any handler) and user feedback (which must print to the terminal). We have discussed this before and decided that python's `logging` module can be used for both (given proper namespacing).

2017-01-17 18:57 UTC, SantiagoTorres approved these changes

2017-01-17 18:57 UTC, merged