Added CONTRIBUTING.md
in-toto/in-toto pull request #751
Opened 2024-05-15 12:00 UTC by DarikshaAnsari

Fixes issue #749 :

Description:

The current in-toto repository has no contributing file, and the only information documented is available [here](https://in-toto.readthedocs.io/en/latest/installing.html), making it challenging for new contributors to get started. This issue aims to add a new contributing file to provide comprehensive and user-friendly instructions for potential contributors.

Proposed Changes:

- [ ]  Quick Start Guide: Add basic steps for contributing.
- [ ]  Installation Instructions: Provide detailed setup instructions.
- [ ]  Contribution Guidelines: Expand on coding standards, testing requirements, and PR process.
- [ ]  DCO Signing: Explain the importance and provide signing instructions.
- [ ]  Testing Instructions: Include tox usage and manual testing guidelines.
- [ ]  Code Formatting: Add guidelines for consistent code formatting.
- [ ]  Documentation Building: Provide instructions for local documentation generation.

2024-05-15 12:06 UTC, DarikshaAnsari commented
@lukpueh I have change the file location. PTAL!

2024-05-16 07:54 UTC, lukpueh requested changes
This is great! Many thanks!! I only have a few minor comments:

- I think we should make the headings less prominent to put more emphasis on the contents (see inline code suggestions).
- Links to `venv` and `git --sign-off` docs are probably helpful (see inline code suggestions).
- The manual test snippet probably does not work. Please fix (see inline comment).
- Would you mind adding a link to this page in https://github.com/in-toto/in-toto?tab=readme-ov-file#governance-and-contributing?

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +# Quick Start Guide
```suggestion
## Quick Start Guide
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +## 1. Clone the Repository
```suggestion
### 1. Clone the Repository
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +## 2. Install Development Dependencies
```suggestion
### 2. Install Development Dependencies
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +## 3. Review Contribution Guidelines
```suggestion
### 3. Review Contribution Guidelines
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +## 4. Sign the Developer Certificate of Origin (DCO)
```suggestion
### 4. Sign the Developer Certificate of Origin (DCO)
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +## 5. Run Tests
```suggestion
### 5. Run Tests
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +### Manual Testing
```suggestion
#### Manual Testing
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +## Code Formatting
```suggestion
#### Code Formatting
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +## Build Documentation
```suggestion
#### Build Documentation
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +Navigate to the project root directory and install development dependencies using pip:
```suggestion
Navigate to the project root directory and install development dependencies using pip
(using [venv](https://docs.python.org/3/library/venv.html) is recommended):
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +All contributors must sign the Developer Certificate of Origin (DCO) by adding a "Signed-off-by" line to their commit messages. This indicates your acceptance of the DCO. You can do this by appending
```suggestion
All contributors must sign the Developer Certificate of Origin (DCO) by adding a "Signed-off-by" line to their commit messages. This indicates your acceptance of the DCO. You can do this by appending the following line to each commit message (see [git commit –signoff](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff)):
```

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +```kotlin
kotlin? :D

2024-05-16 07:54 UTC, lukpueh commented on doc/CONTRIBUTING.md
> +python runtests.py <test_file.py>
Did you try this? I don't think it works. To run a test manually, you'll have to invoke the test file directly.

2024-05-17 07:34 UTC, lukpueh commented
> Would you mind adding a link to this page in https://github.com/in-toto/in-toto?tab=readme-ov-file#governance-and-contributing?

Apart from the link this looks great!

2024-05-17 08:32 UTC, DarikshaAnsari commented
I have added link here in contribution guidelines,

![Screenshot 2024-05-17 140108](https://github.com/in-toto/in-toto/assets/100822529/c51b9e96-b424-40ea-9291-bc49dbfb1279)

2024-05-17 09:07 UTC, lukpueh commented
Ah, okay, I was suggesting to add a link, which points to docs/CONTRIBUTING.md, here:

https://github.com/in-toto/in-toto/blob/659942bde1cd732b0b9449445f9769b2def6aeb1/README.md#L153-L156

E.g.

```markdown
 For information about in-toto's governance and contributing guidelines, see 
 [GOVERNANCE.md](GOVERNANCE.md) and [CONTRIBUTING.md](doc/CONTRIBUTING).md.
 ```

2024-05-17 10:09 UTC, lukpueh commented
> Ah, okay, I was suggesting to add a link, which points to docs/CONTRIBUTING.md, here:
> 
> https://github.com/in-toto/in-toto/blob/659942bde1cd732b0b9449445f9769b2def6aeb1/README.md#L153-L156
> 
> E.g.
> 
> ```
>  For information about in-toto's governance and contributing guidelines, see 
>  [GOVERNANCE.md](GOVERNANCE.md) and [CONTRIBUTING.md](doc/CONTRIBUTING).md.
> ```

There still seems to be a misunderstanding. I was asking to make the suggested change in **REAMDE.md**. If you click on the link above, you'll get directly to the section, which I wanted you to update

2024-05-17 11:21 UTC, lukpueh commented on README.md
> + [GOVERNANCE.md](GOVERNANCE.md) and [CONTRIBUTING.md](doc/CONTRIBUTING).
```suggestion
For information about in-toto's governance and contributing guidelines, see 
[GOVERNANCE.md](GOVERNANCE.md) and [CONTRIBUTING.md](doc/CONTRIBUTING.md).
```

2024-05-21 08:07 UTC, lukpueh approved these changes

2024-05-21 08:08 UTC, merged

2024-05-21 08:08 UTC, lukpueh commented
Thanks!